##
## /*+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
## + Copyright 2025. NHN Academy Corp. All rights reserved.
## + * While every precaution has been taken in the preparation of this resource,  assumes no
## + responsibility for errors or omissions, or for damages resulting from the use of the information
## + contained herein
## + No part of this resource may be reproduced, stored in a retrieval system, or transmitted, in any
## + form or by any means, electronic, mechanical, photocopying, recording, or otherwise, without the
## + prior written permission.
## +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*/
##
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.database=h2
#spring.jpa.open-in-view=false
## swagger information
#springdoc.packages-to-scan=com.nhnacademy.user.controller
#springdoc.default-consumes-media-type=application/json;charset=UTF-8
#springdoc.default-produces-media-type=application/json;charset=UTF-8
#springdoc.swagger-ui.path=/
#springdoc.swagger-ui.disable-swagger-default-url=true
#springdoc.swagger-ui.display-request-duration=true
#springdoc.swagger-ui.operations-sorter=alpha